return {
	-- "None" page is an empty page that opens when the native codes
	-- sends out a navigation event with no pages specified. This page
	-- option should be removed once we remove this navigation event.
	None = "None",
	Startup = "Startup",
	Login = "Login",
	WeChatLoginWrapper = "WeChatLoginWrapper",
	Home = "Home",
	Games = "Games",
	Catalog = "Catalog",
	ItemDetails = "ItemDetails",
	GamesList = "GamesList",
	GameDetail = "GameDetail",
	SearchPage = "SearchPage",
	AvatarEditor = "AvatarEditor",
	AvatarExperienceLandingPage = "AvatarExperienceLandingPage",
	Chat = "Chat",
	Discussions = "Discussions",
	ShareGameToChat = "ShareGameToChat",
	More = "More",
	SimplifiedMore = "SimplifiedMore",
	CJVMore = "CJVMore",
	About = "About",
	CJVAbout = "CJVAbout",
	Settings = "Settings",
	DevSubs = "DevSubs",
	Trades = "Trades",
	Events = "Events",
	BuildersClub = "BuildersClub",
	GenericWebPage = "GenericWebPage",
	SettingsSubPage = "SettingsSubPage",
	YouTubePlayer = "YouTubePlayer",
	PurchaseRobux = "PurchaseRobux",
	Notifications = "Notifications",
	MyFeed = "MyFeed",
	LogoutConfirmation = "LogoutConfirmation",
	AddFriends = "AddFriends",
	ViewUserProfile = "ViewUserProfile",
	ViewProfile = "ViewProfile",
	CharacterSelectionPage = "CharacterSelectionPage",
	UsernameSelectionPage = "UsernameSelectionPage",
	PasswordSelectionPage = "PasswordSelectionPage",
	SignUpVerificationPage = "SignUpVerificationPage",
	SinglePageSignUp = "SinglePageSignUp",
	Landing = "Landing",
	Birthday = "Birthday",
	LoginNative = "LoginNative",
	CaptchaNative = "CaptchaNative",
	TwoStep = "TwoStep",
	ViewFriends = "ViewFriends",
	SellItemPage = "SellItemPage",
	ResellersPage = "ResellersPage",
	ShareSheet = "ShareSheet",
}
