return {
	PlacesList = "PlacesList",
	PeopleList = "PeopleList",
	GameDetailMore = "GameDetailMore",
	PurchaseGame = "PurchaseGame",
	PurchaseGameRobuxShortfall = "PurchaseGameRobuxShortfall",
	LeaveRobloxAlert = "LeaveRobloxAlert",
	ConfirmSignOut = "ConfirmSignOut",
	PremiumMigrationNotice = "PremiumMigrationNotice",
	AutoUpgradePrompt = "AutoUpgradePrompt",
	DevSubMore = "DevSubMore",
	DevSubConfirmCancel = "DevSubConfirmCancel",
	PurchaseCatalogItem = "PurchaseCatalogItem",
	LeaveCatalogToAvatarPrompt = "LeaveCatalogToAvatarPrompt",
	CatalogContextMenu = "CatalogContextMenu",
	SignUpBirthdayPickerOverlay = "SignUpBirthdayPickerOverlay",
	CategoryFiltersPrompt = "CategoryFiltersPrompt",
	PriceFilterPrompt = "PriceFilterPrompt",
}
